{"name": "test_add[int_fail]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 2 == 8\n +  where 2 = round(2, 2)", "trace": "self = <testing.test_calc.TestCalc object at 0x00000280BDAF2CA0>\ncal = <pythoncode.calculator.Calculator object at 0x00000280BDB369D0>, a = 0, b = 2, expect = 8\n\n    @pytest.mark.run(order=1)\n    @pytest.mark.parametrize('a,b,expect',get_Add_Datas()[0],ids=get_Add_Datas()[1])\n    def test_add(self,cal,a,b,expect):\n        result = cal.add(a,b)\n>       assert round(result,2)==expect\nE       assert 2 == 8\nE        +  where 2 = round(2, 2)\n\ntest_calc.py:46: AssertionError"}, "attachments": [{"name": "stdout", "source": "f16e04fa-6960-48b7-a112-75fa09965cad-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "a", "value": "0"}, {"name": "b", "value": "2"}, {"name": "expect", "value": "8"}], "start": 1603069343061, "stop": 1603069343061, "uuid": "2ed031fb-b532-421b-bdfa-efd6a981a5c1", "historyId": "3f44eb0b4abf24ba0ac869873885ee34", "testCaseId": "a7b29b08300809261dc069b49da8543b", "fullName": "test_calc.TestCalc#test_add", "labels": [{"name": "tag", "value": "run(order=1)"}, {"name": "suite", "value": "test_calc"}, {"name": "subSuite", "value": "TestCalc"}, {"name": "host", "value": "MS-NNZIEJQMVEHP"}, {"name": "thread", "value": "5200-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calc"}]}