{"name": "test_mul[int_fail]", "status": "failed", "statusDetails": {"message": "AssertionError: assert -4 == 4\n +  where -4 = round(-4, 2)", "trace": "self = <testing.test_calc.TestCalc object at 0x00000280BDBC5460>\ncal = <pythoncode.calculator.Calculator object at 0x00000280BDB369D0>, a = -2, b = 2, expect = 4\n\n    @pytest.mark.run(order=3)\n    @pytest.mark.parametrize('a,b,expect',get_Mul_Datas()[0],ids=get_Mul_Datas()[1])\n    def test_mul(self,cal,a,b,expect):\n        result = cal.mul(a,b)\n>       assert round(result,2) == expect\nE       assert -4 == 4\nE        +  where -4 = round(-4, 2)\n\ntest_calc.py:69: AssertionError"}, "attachments": [{"name": "stdout", "source": "1b33bb99-57d8-419e-8559-e9344ab62fff-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "a", "value": "-2"}, {"name": "b", "value": "2"}, {"name": "expect", "value": "4"}], "start": 1603069343312, "stop": 1603069343312, "uuid": "3e3a9ebd-164b-49b8-bfc3-f1316557fcd7", "historyId": "6cf5e9233944b3f6d806b9fb371da856", "testCaseId": "463eb02829151a13063664521f3c4534", "fullName": "test_calc.TestCalc#test_mul", "labels": [{"name": "tag", "value": "run(order=3)"}, {"name": "suite", "value": "test_calc"}, {"name": "subSuite", "value": "TestCalc"}, {"name": "host", "value": "MS-NNZIEJQMVEHP"}, {"name": "thread", "value": "5200-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calc"}]}